/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Reservaciones;

import java.awt.Dimension;
import java.awt.Graphics;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author BENHUR
 */
public class mesa2 extends javax.swing.JPanel {
public void paintComponent(Graphics g){
        Dimension   tam=getSize();
        ImageIcon imagen=new ImageIcon(new ImageIcon(getClass().getResource("/imagen/mesas.jpg")).getImage());
       g.drawImage(imagen.getImage(), 0,0,tam.width,tam.height,null);}
    /**
     * Creates new form mesa2
     */
    public mesa2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnrese = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txt2 = new javax.swing.JTextField();

        btnrese.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnrese.setForeground(new java.awt.Color(0, 51, 51));
        btnrese.setText("RESERVAR");
        btnrese.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreseActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MESA PARA DOS PERSONAS:");

        txt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
            .addGroup(layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(btnrese)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(btnrese)
                .addContainerGap(116, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt2ActionPerformed

    private void btnreseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreseActionPerformed
int n2= Integer.parseInt(txt2.getText());
    if(n2>=1 && n2<=4){
        int p;
        p=4-n2;
        JOptionPane.showMessageDialog(btnrese,"usted a reservado "+n2+ " mesas");
        JOptionPane.showMessageDialog(btnrese,"aun quedan "+p+ " por reservar");
    }else{
        JOptionPane.showMessageDialog(btnrese,"mesas insuficientes");
        JOptionPane.showMessageDialog(btnrese,"Solo contamos con 4 mesas para 2 persona como maximo");
    }
    }//GEN-LAST:event_btnreseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnrese;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txt2;
    // End of variables declaration//GEN-END:variables
}
