/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Reservaciones;

import java.awt.Dimension;
import java.awt.Graphics;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author BENHUR
 */
public class mesa4 extends javax.swing.JPanel {
  public void paintComponent(Graphics g){
        Dimension   tam=getSize();
        ImageIcon imagen=new ImageIcon(new ImageIcon(getClass().getResource("/imagen/mesas.jpg")).getImage());
       g.drawImage(imagen.getImage(), 0,0,tam.width,tam.height,null);}
    /**
     * Creates new form mesa4
     */
    public mesa4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnrese = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txt4 = new javax.swing.JTextField();

        btnrese.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnrese.setText("RESERVAR");
        btnrese.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreseActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MESA PARA CUATRO PERSONAS:");

        txt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnrese)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(txt4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(btnrese)
                .addContainerGap(109, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt4ActionPerformed

    private void btnreseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreseActionPerformed
int n4= Integer.parseInt(txt4.getText());
    if(n4>=1 && n4<=5){
        int p;
        p=2-n4;
        JOptionPane.showMessageDialog(btnrese,"usted a reservado "+n4+ " mesas");
        JOptionPane.showMessageDialog(btnrese,"aun quedan "+p+ " por reservar");
    }else{
        JOptionPane.showMessageDialog(btnrese,"mesas insuficientes");
        JOptionPane.showMessageDialog(btnrese,"Solo contamos con 2 mesas para 4 persona como maximo");
    }
    }//GEN-LAST:event_btnreseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnrese;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txt4;
    // End of variables declaration//GEN-END:variables
}
