/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Reservaciones;

import java.awt.Dimension;
import java.awt.Graphics;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author BENHUR
 */
public class mesa3 extends javax.swing.JPanel {
  public void paintComponent(Graphics g){
        Dimension   tam=getSize();
        ImageIcon imagen=new ImageIcon(new ImageIcon(getClass().getResource("/imagen/mesas.jpg")).getImage());
       g.drawImage(imagen.getImage(), 0,0,tam.width,tam.height,null);}
    /**
     * Creates new form mesa3
     */
    public mesa3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnrese = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txt3 = new javax.swing.JTextField();

        btnrese.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnrese.setText("RESERVAR");
        btnrese.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreseActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MESA PARA TRES PERSONAS:");

        txt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(btnrese)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 41, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txt3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(btnrese)
                .addContainerGap(124, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt3ActionPerformed

    private void btnreseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreseActionPerformed
int n3= Integer.parseInt(txt3.getText());
    if(n3>=1 && n3<=5){
        int p;
        p=3-n3;
        JOptionPane.showMessageDialog(btnrese,"usted a reservado "+n3+ " mesas");
        JOptionPane.showMessageDialog(btnrese,"aun quedan "+p+ " por reservar");
    }else{
        JOptionPane.showMessageDialog(btnrese,"mesas insuficientes");
        JOptionPane.showMessageDialog(btnrese,"Solo contamos con 3 mesas para 3 persona como maximo");
    }
    }//GEN-LAST:event_btnreseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnrese;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txt3;
    // End of variables declaration//GEN-END:variables
}
