/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Sistuni.egcc.CobroCineApp.view;

import Sistuni.egcc.CobroCineApp.controller.CineController;
import Sistuni.egcc.CobroCineApp.service.Martes;
import javax.swing.JOptionPane;

/**
 *
 * @author Diego
 */
public class MartesView extends javax.swing.JPanel {

    /**
     * Creates new form MartesView
     */
    
    CineController control;
    Martes mar;
    public MartesView() {
        initComponents();
        
        control=new CineController();
        mar=new Martes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel3 = new javax.swing.JLabel();
        cbpeli = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        txtAdult = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNiñ = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btn2d = new javax.swing.JRadioButton();
        btn3d = new javax.swing.JRadioButton();
        btn4d = new javax.swing.JRadioButton();
        btnProcesar = new javax.swing.JButton();

        jLabel3.setText("Película: ");

        cbpeli.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "La bruja", "Madagascar", "Deadpool", "Zootopia", "Chucky", "Titanic" }));

        jLabel1.setText("Ingrese cantidad de adultos: ");

        jLabel2.setText("Ingrese cantidad de niños: ");

        jLabel4.setText("Tipo: ");

        buttonGroup1.add(btn2d);
        btn2d.setText("2d");
        btn2d.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn2dMouseClicked(evt);
            }
        });

        buttonGroup1.add(btn3d);
        btn3d.setText("3d");
        btn3d.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn3dMouseClicked(evt);
            }
        });

        buttonGroup1.add(btn4d);
        btn4d.setText("4d");
        btn4d.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn4dMouseClicked(evt);
            }
        });

        btnProcesar.setText("Procesar");
        btnProcesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcesarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn2d)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn3d)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn4d))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtAdult)
                                .addComponent(cbpeli, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtNiñ, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnProcesar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbpeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtAdult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNiñ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(btn2d)
                    .addComponent(btn3d)
                    .addComponent(btn4d))
                .addGap(18, 18, 18)
                .addComponent(btnProcesar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnProcesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcesarActionPerformed
        // TODO add your handling code here:
        
        //Datos
        String pelicula;
        float precioadult,precioniño;
        if(txtNiñ.getText().equals("") || txtAdult.getText().equals("")){
             mar.setCantAdult(0);
             mar.setCantNiñ(0);
             JOptionPane.showMessageDialog(null, "Completar espacios");
         }
         else{
        mar.setCantNiñ(Integer.parseInt(txtNiñ.getText()));
        mar.setCantAdult(Integer.parseInt(txtAdult.getText()));
        }
        //Proceso
        
        if(btn2d.isSelected() || btn3d.isSelected() || btn4d.isSelected()){
            if("2d".equals(mar.getTipo()))
                mar.setPrecio();
            else if("3d".equals(mar.getTipo()))
                mar.setPrecio(mar.getTipo());
            else 
                mar.setPrecio(mar.getTipo());


            precioadult=mar.getPrecio();

            precioniño=control.precioNiño(precioadult,mar);

            float total=control.calcularTotal(precioadult, precioniño,mar);

            //Reporte
        pelicula=cbpeli.getSelectedItem().toString();
           
        String repo="--------CINE---------\n";
         repo+="Pelicula:           "+pelicula+"\n";
        repo+="Entradas adultos:    "+mar.getCantAdult()+"\n";
        repo+="Entradas niños:      "+mar.getCantNiñ()+"\n";
        repo+="Total a pagar:       "+total;
                        
            JOptionPane.showMessageDialog(null,repo);
            
            //Reinicio
            txtAdult.setText("");
            txtNiñ.setText("");
            cbpeli.setSelectedIndex(0);
            }
        else{
            
            JOptionPane.showMessageDialog(null, "Seleccione tipo de pelicula");
        }
    }//GEN-LAST:event_btnProcesarActionPerformed

    private void btn2dMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn2dMouseClicked
        // TODO add your handling code here:
        mar.setTipo(btn2d.getLabel());
    }//GEN-LAST:event_btn2dMouseClicked

    private void btn3dMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn3dMouseClicked
        // TODO add your handling code here:
        mar.setTipo(btn3d.getLabel());
    }//GEN-LAST:event_btn3dMouseClicked

    private void btn4dMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn4dMouseClicked
        // TODO add your handling code here:
        mar.setTipo(btn4d.getLabel());
    }//GEN-LAST:event_btn4dMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btn2d;
    private javax.swing.JRadioButton btn3d;
    private javax.swing.JRadioButton btn4d;
    private javax.swing.JButton btnProcesar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbpeli;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtAdult;
    private javax.swing.JTextField txtNiñ;
    // End of variables declaration//GEN-END:variables
}
