/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pe.davidgarciabalarezo.view;

import com.restfb.Connection;
import com.restfb.DefaultFacebookClient;
import com.restfb.FacebookClient;
import com.restfb.Parameter;
import com.restfb.json.JsonObject;
import com.restfb.types.Post;
import com.restfb.types.User;
import java.awt.Component;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.net.URL;
import java.util.List;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Alumno
 */
public class MiPerfilView extends javax.swing.JInternalFrame {

    /**
     * Creates new form MiPerfilView
     */
    public MiPerfilView() {
        initComponents();
        
        //Conectar fb
        try{
        String atoken = AccesoView.txtAccessToken.getText();
        String urlimg="";
        BufferedImage bi;
        FacebookClient facebookClient = new DefaultFacebookClient(atoken);
        User users = facebookClient.fetchObject("me", User.class);   
        this.setTitle("A Cuenta Facebook"+"[ "+users.getName() + "]");
        
         String id ="";
         id = users.getId();
         urlimg = "http://graph.facebook.com/"+id+"/picture?type=large";
         System.out.println("urlimg:"+urlimg);
         

            //bi = ImageIO.read( MiPerfilView.class.getResource(urlimg));
     
      
        //ImageIcon icono = new ImageIcon(bi);
         mePicture.setIcon(new javax.swing.ImageIcon(urlimg) );
         mePicture.setVisible(true);
        // mePicture.setIcon(new javax.swing.ImageIcon(users.getPicture().toString())); // NOI18N
        // jPanel1.add(mePicture);
        // mePicture.setBounds(0, 0, 210, 170);                
        //ImageIcon icon = new ImageIcon(url);              
        //JLabel label = new JLabel("some text");  
        //mePicture.setIcon(icon);  
            
        }
        catch (Exception e) {
            System.out.println("Error -----------------------");
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        mePicture = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Mi Perfil");

        jPanel1.setLayout(null);

        mePicture.setIcon(new javax.swing.ImageIcon("C:\\davidgarciabalarezo\\AppFb\\src\\pe\\davidgarciabalarezo\\recursos\\um.png")); // NOI18N
        jPanel1.add(mePicture);
        mePicture.setBounds(0, 0, 210, 170);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 566, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(311, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel mePicture;
    // End of variables declaration//GEN-END:variables
}
